#!/usr/bin/env python
# -*- coding: utf-8 -*-

# 在HSI域对强度值进行模糊化处理
# import time

import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt
from numpy import exp

from HSI_RGB import rgb2hsi, hsi2rgb




if __name__ == '__main__':
    img = cv.imread('./result19482.jpg')
    print(img)
